apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web
    app: phonebook
spec:
  selector:
    name: web 
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30001
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: phonebook
    spec:
      containers: 
        - image: yurttav/phonebook_web:latest
          imagePullPolicy: Always
          name: myweb
          ports: 
            - containerPort: 80
          env:
          - name: MYSQL_DATABASE_HOST
            value: db-service
          - name: MYSQL_DATABASE
            value: phonebook
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: rootpass
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 80m			  