apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mysql
    app: phonebook1
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    #tier: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql
        app: phonebook1
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        # - name: MYSQL_DATABASE_HOST
        #   value: db-service
        - name: MYSQL_DATABASE
          value: phonebook_db
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
